Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/precise32"
	config.vm.define "node1" do |node|
	  #config.vm.network :forwarded_port, guest: 80, host: 4567
	  config.vm.network :private_network, ip: "192.168.33.71"
	end
	config.vm.define "node2" do |node|
	  #config.vm.network :forwarded_port, guest: 80, host: 4567
	  config.vm.network :private_network, ip: "192.168.33.72"
	end
end
